name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: vimtor/action-zip@v1
        with:
          files: public/resources
          dest: resources.zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: resources.zip
          generateReleaseNotes: true