name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Archive folder
        uses: vimtor/action-zip@v1
        with:
          files: public/resources
          dest: resources.zip

      - name: Create a new release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: resources.zip
          generateReleaseNotes: true